### ISSUE TITLE
TypeError: Object.fromEntries is not a function

### ISSUE THREAD

**Issue by sinchang** [antfu/export-size#1]
OS: Windows

Node: 10.16.3

After running `npx export-size uuid`, throw a error called `TypeError: Object.fromEntries is not a function`

![image](https://user-images.githubusercontent.com/3297859/97404130-90005e80-1930-11eb-8bb2-281eae7cbc22.png)

**Comment by sinchang** [comment]
it is working after upgrading esbuild to v0.7.21.

**Comment by antfu** [comment]
Deps updated. Thanks.
